### PR TITLE
 Fixed deprecated selectors: Replaced pseudo-selectors and syntax selectors

### PR DESCRIPTION
**Pull request by polynoman**
I fixed the things mentioned by the editor. No more deprecation warnings are shown after the replacements.

### CODE REVIEW

**Review by kodemaan — APPROVED** [review]

**Comment by schmty** [comment]
ping?

**Comment by MCDELTAT** [comment]
Can we get this merged? I see the maintainer is active on GitHub, I like the color scheme but get bothered by that Deprecation warning.

**Comment by c0nfleis** [comment]
Any ideas on when this will be merged? I love the theme!

**Comment by schmty** [comment]
it seems @hamxiaoz may be inactive. Best thing may be to just fork it and publish a separate apm package

**Comment by MCDELTAT** [comment]
It already has been forked and is on apm as 'monokai-slate2'. It's simply the exact same thing as the pull request on this issue. I'm using it right now, looks the same with no deprecation warnings.

**Comment by schmty** [comment]
@MCDELTAT awesome, I'd recommend others in this pull thread give that a look!

**Comment by hamxiaoz** [comment]
sorry guys have been idle for a while, it's just merged.

**Pull request merged**
